name: shotcut
version: '19.06.15'
summary: Free, cross-platform, open source video editor
description: >
  Shotcut is a free, open source, cross-platform video editor for Windows,
  Mac and Linux. Major features include support for a wide range of formats;
  no import required meaning native timeline editing; Blackmagic Design
  support for input and preview monitoring; and resolution support to 4k.

grade: stable
confinement: classic

apps:
  shotcut:
    command: Shotcut.app/shotcut
  ffmpeg:
    command: Shotcut.app/ffmpeg
  ffplay:
    command: Shotcut.app/ffplay
  ffprobe:
    command: Shotcut.app/ffprobe
  melt:
    command: Shotcut.app/melt
  qmelt:
    command: Shotcut.app/qmelt

parts:
  shotcut:
    plugin: dump
    source: 'https://github.com/mltframework/shotcut/releases/download/v19.06.15/shotcut-linux-x86_64-190615.txz'
    source-type: tar
    organize:
      'Shotcut': './'
    build-attributes: [no-patchelf]
